### ISSUE TITLE
FR1.  Tutorial and Techniques Directory

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#1]
|FR1.  Tutorial and Techniques Directory|
|---|
|**Goal**: Provide users with a place to view tutorials and techniques based on platform.
**Stakeholders:** Users|
| **Description:** A user can access this page to view tutorials and techniques that will be helpful to them to learn new art platforms. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/21/2020
|  **Priority:** 2 |

**Comment by SpaceMarine2040** [comment]
Looks good!
