### ISSUE TITLE
FR13. Reference Directory - Changed Scope

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#10]
|FR13. Reference Directory |
|---|
|**Goal**: Users can find what they are looking for by searching on the platform.
**Stakeholders:** Users|
| **Description:** In the reference directory, users can find what they are looking for by searching. The user can choose from any of them or they can search for what they want. Example: A user wants to look for a reference for a watercolor painting , the user can search by water color and all references that match with this criteria will come up.  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/24/2020
|  **Priority:** 3 |

**Comment by amoods** [comment]
Changed searchable to just display history of artwork techniques

**Comment by ashleyusvi** [comment]
Everything's working and looks good! Closing the issue with comment.
