### ISSUE TITLE
FR5. Salesboard

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#16]
|FR5. Salesboard |
|---|
|**Goal**: Allow users to view, purchase, or list artwork. 
**Stakeholders:** Users|
| **Description:** The sales board will contain listings. Each listing contains a preview, a price, and a link to the artist’s profile. Users can look at artists’ profiles to see their artwork and how much the artwork is worth and how to purchase it.  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/24/2020
|  **Priority:** 2 |

**Comment by SpaceMarine2040** [comment]
Links to other pages established.

**Comment by ashleyusvi** [comment]
Page is functional and looks good, closing with comment!
