### ISSUE TITLE
FR9. Reviews for Artist Sale

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#17]
|FR9. Reviews for Artist Sale |
|---|
|**Goal**: Allow users to leave reviews on artwork they have bought from the website.
**Stakeholders:** Users|
| **Description:** When a user of the site buys artwork, they are able to leave a review on how the artwork and purchase was. The review consists of an overall score out of five. The user can also post pictures they took of the purchase made in the review so other users will develop an interest to buy artwork.   |
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/24/2020
|  **Priority:** 3 |

**Comment by shifatunnoor** [comment]
start working from 11/19/2020

**Comment by ashleyusvi** [comment]
Not able to implement in time, closing and removing from project
