### ISSUE TITLE
FR11. Reporting Profiles 

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#18]
|FR11. Reporting Profiles  |
|---|
|**Goal**:  Reporting feature will allow users to report accounts that are abusive.
**Stakeholders:** Users|
| **Description:** When users encounter accounts that are posting things that are hurtful or inappropriate, they will be able to report the profiles so it can be reviewed and taken down if necessary. This is a way to make the user experience the best it can be.   |
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/24/2020
|  **Priority:** 2 |

**Comment by SpaceMarine2040** [comment]
Starting Java implementations.

**Comment by SpaceMarine2040** [comment]
Established Apache Tomcat server and intellij integrations, all dependencies resolved.

**Comment by ashleyusvi** [comment]
Closing this issue but we were not able to complete the requirement. We decided on 12/3 to remove this from the project, we didn't feel this would be necessary to the project.
