### ISSUE TITLE
FR15. Contact Page 

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#19]
|FR15. Contact Page  |
|---|
|**Goal**:  Gives users a way to contact site creators.
**Stakeholders:** Users|
| **Description:** If different platforms are desired to talk with artists or students, links can be provided on the contact page. If there are issues with the site, site creators can be contacted. This includes bugs, errors or reporting profiles.   |
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** 3 |

**Comment by shussain1104** [comment]
Contact Page is up, but message isn't getting received after submitting it in the form

**Comment by shussain1104** [comment]
PHP was added, but message still isn't being sent to email put into code

**Comment by ashleyusvi** [comment]
Not able to get the contact page converted to JSP in time for the presentation, removing this requirement from the project and closing.

**Comment by shussain1104** [comment]
Was able to get the contact page running but without backend. What it will do for now is after pressing the send message now app, it should open up the default mail app on the user's laptop.
