### ISSUE TITLE
FR4. Reactions

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#4]
|FR4. Reactions |
|---|
|**Goal**: Allow users to express what they feel regarding tutorials and posts. 
**Stakeholders:** Users|
| **Description:** When a user sees a picture of artwork or views a tutorial, he/she should be able to leave some kind of reaction to express how they feel/ what they view about the post. Developers will need to focus on giving access to all users to post their reactions while administrators will need to focus on censoring inappropriate reactions/views. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/21/2020
|  **Priority:** 3 |

**Comment by shifatunnoor** [comment]
Working on the html to organize the page.

**Comment by ashleyusvi** [comment]
Closing this issue but we did not include it in the project, we decided that we would not be able to finish this with the time remaining
