### ISSUE TITLE
FR7.  User Submitted Directory 

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#6]
|FR7.  User Submitted Directory |
|---|
|**Goal**: Allow tutors and artists to upload references, techniques, and tutorials.. 
**Stakeholders:** Users, Developers|
| **Description:** Users can upload their documentation regarding artistic techniques through a vetted system of moderators. The administrators will keep track of appropriate and inappropriate content, in order to maintain a steady flow of consumables for end-users. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/21/2020
|  **Priority:** 2 |

**Comment by SpaceMarine2040** [comment]
HTML Skeleton complete, styles established.

**Comment by SpaceMarine2040** [comment]
Completed downloads ability.

**Comment by ashleyusvi** [comment]
Everything looks good on this issue! Closing it with this comment.

**Comment by SpaceMarine2040** [comment]
Using this for Assignment 05!
