### ISSUE TITLE
FR12. Board of Post Questions

### ISSUE THREAD

**Issue by ashleyusvi** [WSU-4110/ArtArchive#9]
|FR12. Board of Post Questions |
|---|
|**Goal**: Give a space for users to post any type of questions they have regarding any site material.
**Stakeholders:** Users|
| **Description:** A separate page will be created where users can post questions regarding any issues or any general questions for posts/tutorials. It’ll be similar to a discussion board, and at the bottom of the page the option to email/ contact the artists who created the tutorials will be given as well.  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/21/2020
|  **Priority:** 2 |

**Comment by shussain1104** [comment]
HTML form is setup, connection to DB is still needed.

**Comment by ashleyusvi** [comment]
Looks good! Will create a new FR for sprint-3 to finish the DB, closing the issue with comment.
